# home/profiles/personal.nix
# ============================================================
# Personal profile — applied on top of home/default.nix.
#
# Contains anything that differs between personal and work:
# AI tools, the `dots` alias that points back to this profile,
# and `tut` (a Mastodon TUI) with a kanagawa-themed config.
# ============================================================
{ pkgs, ... }:
let
  # tut config — TOML, written verbatim to ~/.config/tut/config.toml.
  #
  # Theme palette mirrors nvim/lua/plugins/kanagawa.lua (kanagawa-wave):
  #   bg          #1F1F28  sumiInk1     text          #DCDCDC  fujiWhite
  #   subtle      #727169  konGyo       warning       #E46876  waveRed
  #   carpYellow  #E6C384  username     crystalBlue   #7E9CD8  hint
  #   springBlue  #7DCFFF  status view  oldWhite      #C8C093  status text
  #   sumiInk2    #2A2A37  bars         sumiInk3      #363646  selection bg
  #
  # `editor = "$EDITOR"` defers to nvim (set in home/default.nix).
  # `leader-key = " "` mirrors `vim.g.mapleader` so `<space>q`,
  # `<space>1/2/3` etc. feel like the same muscle memory you
  # already use in neovim.
  #
  # `~/.config/tut/accounts.toml` is intentionally NOT managed by
  # Nix — tut writes it on first login (`tut --new-user`) and it
  # stores OAuth tokens. If you use `pass`/`gopass`, prefix values
  # with `!CMD!` (see tut's README) to pull secrets on demand.
  tutConfig = ''
    # ============================================================
    # tut — Mastodon TUI config
    # Generated by home/profiles/personal.nix — edit there, not here.
    # ============================================================

    [general]
    # Use $EDITOR (nvim) for composing/editing toots.
    editor = "$EDITOR"
    # Ask before favorite/boost/etc. — same prompt habit as `:q!` in vim.
    confirmation = true
    # Click and scroll inside tut like a civilized person.
    mouse-support = true

    # Leader key = space — matches `vim.g.mapleader` in lua/config/lazy.lua.
    leader-key = " "
    leader-timeout = 1000

    # Pane layout: feeds on the left, stacked vertically (one column).
    list-placement = "left"
    list-split = "row"
    list-proportion = 1
    content-proportion = 2

    # Dates: same-day toots show just the time; toots up to 28 days old
    # show as "1y2m1d"-style relative; older ones show a full timestamp.
    date-format = "2006-01-02 15:04"
    date-tody-format = "15:04"
    date-relative = 28

    # Always quote the toot you're replying to — like vim's `:r !` pulling context.
    quote-reply = true
    # `:timeline home` etc. open in a new pane instead of replacing the current one.
    commands-in-new-pane = true
    # Show "tut — @user@instance — home" in the terminal title + top bar.
    terminal-title = 1
    show-icons = true
    short-hints = false

    # ---- Default timelines open at launch ----------------------
    [[general.timelines]]
    name = "home"
    type = "home"

    [[general.timelines]]
    name = "notifications"
    type = "notifications"
    keys = ["n", "N"]

    # ---- Leader actions (space-prefixed, like nvim) ------------
    # <space>q      close current pane           (cf. closing a buffer)
    # <space>1/2/3  focus pane 0/1/2             (cf. buffer/tab shortcuts)
    # <space>s      vertical split (column)
    # <space>S      horizontal split (row)
    [[general.leader-actions]]
    type = "close-pane"
    shortcut = "q"

    [[general.leader-actions]]
    type = "pane"
    data = "0"
    shortcut = "1"

    [[general.leader-actions]]
    type = "pane"
    data = "1"
    shortcut = "2"

    [[general.leader-actions]]
    type = "pane"
    data = "2"
    shortcut = "3"

    [[general.leader-actions]]
    type = "list-split"
    data = "column"
    shortcut = "s"

    [[general.leader-actions]]
    type = "list-split"
    data = "row"
    shortcut = "S"

    # ============================================================
    # Media openers — defer to xdg-open (uses your MIME handlers).
    # ============================================================
    [media]
    delete-temp-files = true

    [media.image]
    program = "TUT_OS_DEFAULT"
    terminal = false

    [media.video]
    program = "TUT_OS_DEFAULT"
    terminal = false

    [media.audio]
    program = "TUT_OS_DEFAULT"
    terminal = false

    [media.link]
    program = "TUT_OS_DEFAULT"
    terminal = false

    # ============================================================
    # Desktop notifications (libnotify) — only the loud ones.
    # ============================================================
    [desktop-notification]
    followers = true
    favorite = false
    mention = true
    update = false
    boost = true
    poll = true
    posts = false

    # ============================================================
    # Theme — inline overrides on top of theme="none".
    # All colors from the kanagawa-wave palette (see comment at top
    # of the let-binding in home/profiles/personal.nix).
    # ============================================================
    [style]
    theme = "none"
    xrdb-prefix = "guess"

    background = "#1F1F28"
    text = "#DCDCDC"
    subtle = "#727169"
    warning-text = "#E46876"

    text-special-one = "#E6C384"
    text-special-two = "#7E9CD8"

    top-bar-background = "#2A2A37"
    top-bar-text = "#DCDCDC"
    status-bar-background = "#2A2A37"
    status-bar-text = "#C8C093"
    status-bar-view-background = "#363646"
    status-bar-view-text = "#7DCFFF"
    command-text = "#E6C384"

    list-selected-background = "#363646"
    list-selected-text = "#E6C384"
    list-selected-inactive-background = "#2A2A37"
    list-selected-inactive-text = "#7E9CD8"

    controls-text = "#C8C093"
    controls-highlight = "#E6C384"

    autocomplete-background = "#2A2A37"
    autocomplete-text = "#DCDCDC"
    autocomplete-selected-background = "#7E9CD8"
    autocomplete-selected-text = "#1F1F28"

    button-color-one = "#7E9CD8"
    button-color-two = "#1F1F28"

    timeline-name-background = "#2A2A37"
    timeline-name-text = "#7DCFFF"
  '';
in
{
  # The personal knowledge vault wiring (global agent pointers + the
  # librarian skill). Personal profile only — the vault's contents must
  # never land on employer hardware. See home/vault.nix.
  imports = [ ../vault.nix ];

  mycfg.kanata.enable = true;

  home.packages = with pkgs; [
    claude-code       # Anthropic's Claude Code CLI
    aerc              # Terminal-based email client
    tut               # TUI Mastodon client with vim-inspired keys
  ];

  # tut ships no home-manager module, so we drop its TOML config
  # straight into ~/.config/tut/config.toml via xdg.configFile.
  # The accounts.toml file (OAuth tokens) is left to tut itself —
  # run `tut --new-user` once after `dots` to log in.
  xdg.configFile."tut/config.toml".text = tutConfig;

  programs.zsh.shellAliases = {
    dots = "home-manager switch --flake ~/dotfiles#personal --impure";
  };
}